const state = { config: null, token: localStorage.getItem('ec_admin_token') || '', user: null, demands: [], content: [] };
const $ = (s) => document.querySelector(s);
const loginView = $('#loginView'), appView = $('#appView'), panel = $('#panel'), pageTitle = $('#pageTitle');

async function config(){ if(state.config) return state.config; const r=await fetch('/api/config'); if(!r.ok) throw new Error('Servidor não configurado.'); return state.config=await r.json(); }
async function api(action, options={}, params={}){ const qs=new URLSearchParams({action,...params}); const url=`/api/admin?${qs.toString()}`; const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${state.token}`,...(options.headers||{})}}); const d=await r.json().catch(()=>({})); if(r.status===401){logout(); throw new Error('Sessão expirada.');} if(!r.ok) throw new Error(d.error||'Erro no painel.'); return d; }
async function login(email,password){ const c=await config(); const r=await fetch(`${c.supabaseUrl}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:c.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})}); const d=await r.json(); if(!r.ok) throw new Error(d.error_description||d.msg||'Login inválido.'); state.token=d.access_token; localStorage.setItem('ec_admin_token',state.token); await boot(); }
function logout(){localStorage.removeItem('ec_admin_token');state.token='';appView.hidden=true;loginView.hidden=false;}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginFeedback').textContent='Entrando…';try{await login($('#email').value,$('#password').value);$('#loginFeedback').textContent='';}catch(err){$('#loginFeedback').textContent=err.message;}});
$('#logoutBtn').addEventListener('click',logout);
document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>showPage(btn.dataset.page)));

async function boot(){ try{ await Promise.all([loadDemands(),loadContent()]); loginView.hidden=true;appView.hidden=false;showPage('dashboard'); }catch(err){ if(state.token) $('#loginFeedback').textContent=err.message; else logout(); } }
async function loadDemands(){state.demands=(await api('demands')).demands||[];}
async function loadContent(){state.content=(await api('content')).content||[];}
function activate(page){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function showPage(page){activate(page);if(page==='dashboard')renderDashboard();if(page==='demands')renderDemands();if(page==='content')renderContent();}
function renderDashboard(){pageTitle.textContent='Visão geral';const total=state.demands.length,open=state.demands.filter(d=>!['Resolvida','Arquivada'].includes(d.status)).length,resolved=state.demands.filter(d=>d.status==='Resolvida').length,today=new Date().toISOString().slice(0,10),todayCount=state.demands.filter(d=>String(d.created_at).slice(0,10)===today).length;panel.innerHTML=`<div class="cards"><div class="metric"><strong>${total}</strong><span>Total de demandas</span></div><div class="metric"><strong>${todayCount}</strong><span>Recebidas hoje</span></div><div class="metric"><strong>${open}</strong><span>Em aberto</span></div><div class="metric"><strong>${resolved}</strong><span>Resolvidas</span></div></div><div class="section-label">Últimas demandas</div>${demandTable(state.demands.slice(0,8))}`;bindDemandButtons();}
function demandTable(rows){return `<div class="table-wrap"><table><thead><tr><th>Protocolo</th><th>Data</th><th>Nome</th><th>Telefone</th><th>Categoria</th><th>Bairro</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(d=>`<tr><td><b>${esc(d.protocol)}</b></td><td>${new Date(d.created_at).toLocaleString('pt-BR')}</td><td>${esc(d.name)}</td><td>${esc(d.phone)}</td><td>${esc(d.category)}</td><td>${esc(d.neighborhood)}</td><td><span class="pill">${esc(d.status)}</span></td><td><button class="open-btn" data-demand-id="${d.id}">Abrir</button></td></tr>`).join('')||'<tr><td colspan="8">Nenhuma demanda registrada.</td></tr>'}</tbody></table></div>`;}
function renderDemands(){pageTitle.textContent='Denúncias e demandas';panel.innerHTML=demandTable(state.demands);bindDemandButtons();}
function bindDemandButtons(){document.querySelectorAll('[data-demand-id]').forEach(b=>b.onclick=()=>openDemand(b.dataset.demandId));}
function openDemand(id){const d=state.demands.find(x=>x.id===id);if(!d)return;const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card"><div class="modal-top"><div><small>${esc(d.protocol)}</small><h2>${esc(d.kind==='Denúncia'&&d.category==='Causa Animal'?'Denúncia Causa Animal':d.kind)}${d.kind==='Denúncia'&&d.category==='Causa Animal'?'':` — ${esc(d.category)}`}</h2></div><button data-close>×</button></div><div class="details"><div><b>Nome</b><span>${esc(d.name)}</span></div><div><b>Telefone</b><span>${esc(d.phone)}</span></div><div><b>Bairro</b><span>${esc(d.neighborhood)}</span></div><div><b>Local</b><span>${esc(d.address||'-')}</span></div></div><p>${esc(d.message)}</p><div class="attachments">${(d.attachments||[]).map((a,i)=>`<button class="open-btn attachment-btn" data-path="${esc(a.path)}">📎 ${esc(a.name||('Anexo '+(i+1)))}</button>`).join('')||'<span>Sem anexos</span>'}</div><div class="demand-editor"><div class="row"><label>Status<select id="mStatus">${['Nova','Em análise','Encaminhada','Aguardando órgão','Resolvida','Arquivada'].map(x=>`<option ${d.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Prioridade<select id="mPriority">${['Baixa','Média','Alta','Urgente'].map(x=>`<option ${d.priority===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label>Observações internas<textarea id="mNotes" rows="5">${esc(d.internal_notes||'')}</textarea></label><button class="primary" id="saveDemand">Salvar alterações</button></div></div>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.querySelectorAll('.attachment-btn').forEach(btn=>btn.onclick=async()=>{try{const d=await api('attachment',{}, {path:btn.dataset.path});window.open(d.url,'_blank','noopener');}catch(err){alert(err.message);}});modal.querySelector('#saveDemand').onclick=async()=>{const btn=modal.querySelector('#saveDemand');btn.disabled=true;btn.textContent='Salvando…';try{await api('demand',{method:'PUT',body:JSON.stringify({id:d.id,status:modal.querySelector('#mStatus').value,priority:modal.querySelector('#mPriority').value,internal_notes:modal.querySelector('#mNotes').value})});await loadDemands();modal.remove();renderDemands();}catch(err){alert(err.message);}finally{btn.disabled=false;btn.textContent='Salvar alterações';}};}
function renderContent(){pageTitle.textContent='Conteúdo do site';const groups={};state.content.forEach(i=>(groups[i.section||'Geral']??=[]).push(i));panel.innerHTML=Object.entries(groups).map(([section,items])=>`<div class="section-label">${esc(section)}</div><div class="editor-list">${items.map(i=>`<div class="editor" data-content-id="${i.id}"><div class="editor-head"><strong>${esc(i.label||i.content_key)}</strong><span>${esc(i.content_key)} • ${esc(i.content_type)}</span></div>${i.content_type==='text'||i.content_type==='html'?`<textarea>${esc(i.value||'')}</textarea>`:`<input value="${esc(i.value||'')}">`}${i.content_type==='image'?'<input type="file" class="image-upload" accept="image/jpeg,image/png,image/webp" style="margin-top:8px">':''}<div class="editor-actions"><button class="primary save-content">Salvar</button></div></div>`).join('')}</div>`).join('');document.querySelectorAll('.save-content').forEach(btn=>btn.onclick=()=>saveContent(btn.closest('.editor')));document.querySelectorAll('.image-upload').forEach(input=>input.onchange=()=>uploadSiteImage(input));}
async function saveContent(box){const id=box.dataset.contentId,value=(box.querySelector('textarea')||box.querySelector('input:not([type=file])')).value;const btn=box.querySelector('.save-content');btn.disabled=true;btn.textContent='Salvando…';try{await api('content',{method:'PUT',body:JSON.stringify({id,value})});await loadContent();btn.textContent='Salvo ✓';setTimeout(()=>btn.textContent='Salvar',1000);}catch(err){alert(err.message);btn.textContent='Salvar';}finally{btn.disabled=false;}}
function loadImageForOptimization(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível processar esta imagem. Tente JPG, PNG ou WebP.'))};img.src=url;});}

async function optimizeSiteImage(file){
  if(!/^image\/(jpeg|png|webp)$/i.test(file.type)) throw new Error('Formato não suportado. Use JPG, PNG ou WebP.');
  const img=await loadImageForOptimization(file);
  const srcW=img.naturalWidth||img.width;
  const srcH=img.naturalHeight||img.height;
  const targetBytes=750*1024; // mantém o arquivo bem abaixo do limite do Storage
  let maxSide=Math.min(1800,Math.max(srcW,srcH));
  let quality=.82;
  let blob=null;

  for(let pass=0;pass<10;pass++){
    const scale=Math.min(1,maxSide/Math.max(srcW,srcH));
    const width=Math.max(1,Math.round(srcW*scale));
    const height=Math.max(1,Math.round(srcH*scale));
    const canvas=document.createElement('canvas');
    canvas.width=width;canvas.height=height;
    const ctx=canvas.getContext('2d',{alpha:false});
    ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);
    ctx.drawImage(img,0,0,width,height);
    blob=await new Promise(r=>canvas.toBlob(r,'image/webp',quality));
    if(blob && blob.size<=targetBytes) break;
    if(quality>.58) quality-=.07;
    else { maxSide=Math.max(900,Math.round(maxSide*.84)); quality=.74; }
  }

  if(!blob) throw new Error('Não foi possível otimizar a imagem.');
  if(blob.size>950*1024) throw new Error('A foto ainda ficou muito grande após a otimização. Tente outra imagem ou faça uma captura de tela dela antes de enviar.');
  return new File([blob],(file.name.replace(/\.[^.]+$/,'')||'imagem')+'.webp',{type:'image/webp'});
}

async function uploadSiteImage(input){const original=input.files?.[0];if(!original)return;const box=input.closest('.editor'),textInput=box.querySelector('input:not([type=file])'),btn=box.querySelector('.save-content');try{if(btn){btn.disabled=true;btn.textContent='Otimizando imagem…';}const file=await optimizeSiteImage(original);if(btn)btn.textContent=`Enviando ${(file.size/1024).toFixed(0)} KB…`;const c=await config();const path=`cms/${Date.now()}-${crypto.randomUUID()}.webp`;const r=await fetch(`${c.supabaseUrl}/storage/v1/object/${c.siteMediaBucket}/${path}`,{method:'POST',headers:{apikey:c.supabasePublishableKey,Authorization:`Bearer ${state.token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!r.ok){const detail=await r.text().catch(()=> '');let msg=detail||'Falha ao enviar imagem.';if(r.status===413)msg=`A imagem foi otimizada para ${(file.size/1024).toFixed(0)} KB, mas o Storage recusou o envio. Verifique o limite do bucket site-media no Supabase.`;throw new Error(msg);}textInput.value=`${c.supabaseUrl}/storage/v1/object/public/${c.siteMediaBucket}/${path}`;input.value='';if(btn){btn.textContent='Salvando imagem…';}await api('content',{method:'PUT',body:JSON.stringify({id:box.dataset.contentId,value:textInput.value})});await loadContent();if(btn){btn.textContent='Imagem salva ✓';setTimeout(()=>btn.textContent='Salvar',1800);}}catch(err){alert(err.message);if(btn)btn.textContent='Salvar';}finally{if(btn)btn.disabled=false;}}
if(state.token) boot();
